language: ruby

rvm:
  - 2.1.8
  - 2.2.5
  - 2.3.1
  - ruby-head

sudo: false

script: bundle exec rspec

before_install:
  - gem install bundler -v 1.12.1

matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/rails_5.0.gemfile

gemfile:
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
